language: python
python:
    - 3.4
env:
    - DJANGO_VERSION=1.8.17
install:
    # Install django/nose
    - pip install Django==$DJANGO_VERSION
    - pip install django-nose
    # Install cache helper
    - pip install -e .
    - pip install pylibmc
script:
    - python test_project/manage.py test
