language: python
python:
    - 2.7
env:
    - DJANGO_VERSION=1.5.12
    - DJANGO_VERSION=1.6.10
    - DJANGO_VERSION=1.7.5
install:
    # Install django/nose
    - pip install Django==$DJANGO_VERSION
    - pip install django-nose
    # Install cache helper
    - pip install -e .
script:
    - python test_project/manage.py test
