language: python
python:
    - 2.7
env:
    - DJANGO_VERSION=1.5.12
    - DJANGO_VERSION=1.6.10
    - DJANGO_VERSION=1.7.5
install:
    # Install django/nose
    - pip install Django==$DJANGO_VERSION
    # Install cache helper
    - pip install -e .
script:
    - cd test_project
    - python manage.py test -v 2
