dist: xenial
language: python
python:
    - 3.4
    - 3.5
env:
    - DJANGO_VERSION=1.7.11
    - DJANGO_VERSION=1.8.19
    - DJANGO_VERSION=1.9.13
    - DJANGO_VERSION=1.10.8
    - DJANGO_VERSION=1.11.17
    - DJANGO_VERSION=2.0.10
    - DJANGO_VERSION=2.1.4
install:
    - pip install -r requirements.txt
    # Install dev requirements for testing
    - pip install -r dev_requirements.txt
    # Install cache helper
    - pip install -e .
script:
    - python test_project/manage.py test
