name: Test Suite # IMPORTANT: If this name changes you need to update the canceller.yml

# Controls when the action will run.
on:
  # Triggers the workflow on push for the master branch.
  push:
    branches: [ master ]

  # Triggers the workflow on pull request for any branch.
  pull_request:

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [ 3.4, 3.5, 3.6, 3.7 ]
        django-version: [ 1.7.x, 1.8.x, 1.9.x, 1.10.x, 1.11.x, 2.0.x, 2.1.x, 2.2.x, 3.0.x, 3.1.x ]
        exclude:
          - python-version: 3.4
            django-version: 2.1.x
          - python-version: 3.4
            django-version: 2.2.x
          - python-version: 3.4
            django-version: 3.0.x
          - python-version: 3.4
            django-version: 3.1.x
          - python-version: 3.5
            django-version: 1.7.x
          - python-version: 3.5
            django-version: 3.0.x
          - python-version: 3.5
            django-version: 3.1.x
          - python-version: 3.6
            django-version: 1.7.x
          - python-version: 3.7
            django-version: 1.7.x
    defaults:
      run:
        shell: bash
    steps:
      # Checks-out the  repository.
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -q Django==${{ matrix.django-version }}

      - name: Install Cache Helper Package
        run: pip install -e .

      - name: Run tests
        run: python manage.py test
        working-directory: ./test_project
